app = "xbot-crimson-glitter-324"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  LOG_LEVEL = "trace"
  PRIMARY_REGION = "cdg"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  ports = []
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
